# Generated by Django 3.2.20 on 2023-08-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
