# Generated by Django 3.2.20 on 2023-08-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_like_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
